version: '3.8'

services:
  mongo-database:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
       MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
#    volumes:
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks: 
      - mesttra-net

networks: 
  aluraflix-net:
    driver: bridge
    name: mesttra-net
