version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
#      MARIADB_DATABASE: aluraFlix
    ports:
      - '3306:3306'
#    volumes:
#      - './mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql:ro'
    networks:
      - mesttra-net
      
networks:
  backend:
    driver: bridge
    name: mesttra-net
